Update server.yml

diff --git a/.github/workflows/server.yml b/.github/workflows/server.yml
--- a/.github/workflows/server.yml
+++ b/.github/workflows/server.yml
@@ -21,19 +21,19 @@ jobs:
       - name: Update server
         if: success() || failure()
         run: ./setup-auto-mc.sh
-      - name: Setup ZeroTier & connect
+      - name: Setup ngrok
         if: success() || failure()
         env:
-          zerotiernetid: ${{ secrets.ZEROTIERNETID }}
-        run: ./setup-zerotier.sh
-      - name: Run server
-        if: success() || failure()
-        run: ./run-mc.sh
-      - name: Disconnect ZeroTier
-        if: ${{ cancelled() }} || success() || failure()
-        env:
-          zerotiernetid: ${{ secrets.ZEROTIERNETID }}
-        run: ./disconnect-zerotier.sh
+          ngrokauthtoken: ${{ secrets.NGROKAUTHTOKEN }}
+        run: ./setup-ngrok.sh
+*      - name: Run server
+*        if: success() || failure()
+*        run: ./run-mc.sh
+#      - name: Disconnect ZeroTier
+#        if: ${{ cancelled() }} || success() || failure()
+#        env:
+#          zerotiernetid: ${{ secrets.ZEROTIERNETID }}
+#        run: ./disconnect-zerotier.sh
       - name: Upload artifact
         if: ${{ cancelled() }} || success() || failure()
         uses: actions/upload-artifact@v2
@@ -41,6 +41,7 @@ jobs:
           name: server
           path: |
                 server
+                !*ngrok*
                 !server/logs
                 !server/*mixin*
                 !server/*fabric*
